# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b6f5378d2bf31dbb047c8397bab584a9dec957190badc58f73f29271665068e1d00d5be7af927e0f45ffd4d1809eb8a7e5402c63f443e9222fcc16ad3777966

test:
  secret_key_base: d689b3c78c912fc9dd91f2b61e88717e8db88ff7ceffe99c37fbca183c82639e4e13196269cdd8f05d6c5cb91156846853a9cc1f42944e4ebe432d98637ec004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
